### ISSUE TITLE
Change the flow in Restcomm API

### ISSUE THREAD

**Issue by ipsilantide** [RestComm/design#42]
![screen shot 2016-12-13 at 5 54 16 pm](https://cloud.githubusercontent.com/assets/17202395/21151361/e5ee9a9a-c16a-11e6-893c-ce6a29fa8a0e.png)
Questions:
1: Can we modify the credentials from here? If yes we should make it clearer for the user...
2: In the pop up the fields are filled in probably by the browser. Right? 
3: Isn't it simpler to use the credentials we have in dashboard? I am afraid that we are troubling users mind with too many credentials (If I add web triggers access token as well). Is there a reason we need those new credentials? 
4: Right now we have two buttons "Cancel" and "OK". In case of no changes both of them do the same job. Even if we need to keep the credentials this way. We need to change the flow of adding them

**Comment by otsakir** [comment]
@ipsilantide , some internal stuff first. 
* _Username_ and _Password_ refer to a restcomm Account _email_ address and _AuthToken_.
* These credentials are needed to be setup only if the user has any applications that use WebTrigger AND 'Access token' authorization. Otherwise the user can also put the email/AuthToken directly in the WebTrigger request. 

In other words, if we deprecate the 'Access token' in the WebTrigger settings (and all existing applications that use it of course) we don't need this popup.

On to your questions:
1. Yes, we modify the credentials. Maybe have a 'Save' button instead of 'Ok'. Is this what you mean ?
2. Yes, it's a very annoying pre-filling behaviour of the browser.
3. These credentials are a way for RVD to access restcomm. They have to be the same with those in Dashboard. RVD authenticates against restcomm. They are not another set of credentials.
4. Wdym? There is a dialog that changes sth. We have to provide a way to _save_ or _cancel_.
